#!/bin/bash
#SBATCH --job-name=ldsc_h2
#SBATCH --error=%x-%j.error
#SBATCH --out=%x-%j.out
#SBATCH --mem=40G
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --time=7-0:0:0
#conda activate ldsc
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM1.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out .//v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM1.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM2.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM2.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM3.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM3.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM4.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM4.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM5.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM5.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM6.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM6.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM7.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM7.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM8.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM8.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM9.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM9.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM10.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM10.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM11.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM11.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM12.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM12.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM13.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM13.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM14.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM14.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM15.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM15.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM16.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM16.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM17.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM17.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM18.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM18.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM19.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM19.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM20.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM20.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM21.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM21.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM22.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM22.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM23.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM23.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM24.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM24.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM25.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM25.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM26.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM26.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM27.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM27.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM28.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM28.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM29.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM29.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM30.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM30.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM31.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM31.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM32.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM32.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM33.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM33.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM34.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM34.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM35.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM35.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM36.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM36.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM37.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM37.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM38.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM38.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM39.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM39.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM40.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM40.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM41.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM41.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM42.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM42.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM43.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM43.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM44.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM44.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM45.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM45.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM46.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM46.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM47.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM47.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM48.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM48.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM49.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM49.ldsc.res.txt
python ./biosoft/ldsc/ldsc.py --h2 ./v2_NC_revision/simulation_values_res/sim_y_values/beta1_1_h2_0.05_SNPs_500.sim_y/10M.SIM50.glm.logistic.hybrid.txt --ref-ld-chr ./v2_NC_revision//84Tracks/ldscores_sim500/ --w-ld-chr ./ref/Alkesgroup/eur_w_ld_chr/ --out ./v2_NC_revision/simulation_values_res/ldsc_res/y_sim_h2_0.05_SNPs_500/SIM50.ldsc.res.txt
